# Create Test User Script
# Inserts a test admin user into the local PostgreSQL database

Write-Host "============================================" -ForegroundColor Cyan
Write-Host "Creating Test Admin User" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

$env:PGPASSWORD = "55662211@@@"

$email = "admin@truthprotocol.com"
$password = "admin123"

# BCrypt hash for "admin123" using BCryptPasswordEncoder(10)
# Generated by Spring Security BCryptPasswordEncoder
# Note: We must escape the $ signs in the BCrypt hash for PowerShell
$passwordHash = "`$2a`$10`$N9qo8uLOickgx2ZMRZoMye/IY/lGhzzN7mIQGLJ9.OrVLWyJkzJVy"

Write-Host "User Details:" -ForegroundColor Yellow
Write-Host "  Email:    $email" -ForegroundColor White
Write-Host "  Password: $password" -ForegroundColor White
Write-Host "  Role:     ADMIN" -ForegroundColor White
Write-Host "  Credits:  1000.00" -ForegroundColor White
Write-Host ""

# First, try to delete existing user to avoid conflicts
Write-Host "Removing existing user (if exists)..." -ForegroundColor Yellow
$deleteSql = "DELETE FROM users WHERE email = '$email';"
psql -U postgres -d postgres -h localhost -p 5432 -c $deleteSql 2>$null

# Insert new user
Write-Host "Creating new user..." -ForegroundColor Yellow
$insertSql = "INSERT INTO users (email, password_hash, role, kyc_status, credits) VALUES ('$email', '$passwordHash', 'ADMIN', 'APPROVED', 1000.00);"
psql -U postgres -d postgres -h localhost -p 5432 -c $insertSql

if ($LASTEXITCODE -eq 0) {
    Write-Host ""
    Write-Host "✓ Test user created successfully!" -ForegroundColor Green
    Write-Host ""
    Write-Host "============================================" -ForegroundColor Green
    Write-Host "Login Credentials" -ForegroundColor Green
    Write-Host "============================================" -ForegroundColor Green
    Write-Host "Email:    $email" -ForegroundColor Cyan
    Write-Host "Password: $password" -ForegroundColor Cyan
    Write-Host "Role:     ADMIN" -ForegroundColor Cyan
    Write-Host "============================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "Next Steps:" -ForegroundColor Yellow
    Write-Host "1. Start the backend: .\start-dev.ps1" -ForegroundColor White
    Write-Host "2. Test login at: http://localhost:8080/api/v1/auth/login" -ForegroundColor White
    Write-Host ""
} else {
    Write-Host ""
    Write-Host "✗ Failed to create test user" -ForegroundColor Red
    Write-Host "Please check:" -ForegroundColor Yellow
    Write-Host "  - PostgreSQL is running" -ForegroundColor White
    Write-Host "  - Database 'postgres' exists" -ForegroundColor White
    Write-Host "  - Database password is correct" -ForegroundColor White
    Write-Host ""
}

Remove-Item Env:\PGPASSWORD
